# Generated by Django 4.1.3 on 2022-11-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='score',
            field=models.IntegerField(default=100, verbose_name='score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='band_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music_album.band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music_album.album'),
        ),
        migrations.AlterField(
            model_name='albumreviewcomment',
            name='album_review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_album.albumreview'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_album.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='AlbumReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music_album.albumreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
